WebUII/Areas/Administrator/Controllers/FairsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.FW.Context;
using Model.FW.Entity;
using Service.FW.Concrete;

namespace WebUII.Areas.Administrator.Controllers
{
    //[Authorize(Roles = "admin")]
    public class FairsController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        FairService fairService = new FairService();

        // GET: Administrator/Fairs
        public ActionResult Index()
        {
            return View(fairService.GetList());
        }

        // GET: Administrator/Fairs/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fair fair = fairService.GetById(id);
            if (fair == null)
            {
                return HttpNotFound();
            }
            return View(fair);
        }

        // GET: Administrator/Fairs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Fairs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FairName,FirstDay,LastDay,TheNumberOfParticipant")] Fair fair)
        {
            if (ModelState.IsValid)
            {
                fair.ID = Guid.NewGuid();
                fairService.Create(fair);
                return RedirectToAction("Index");
            }

            return View(fair);
        }

        // GET: Administrator/Fairs/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fair fair = fairService.GetById(id);
            if (fair == null)
            {
                return HttpNotFound();
            }
            return View(fair);
        }

        // POST: Administrator/Fairs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FairName,FirstDay,LastDay,TheNumberOfParticipant")] Fair fair)
        {
            if (ModelState.IsValid)
            {
                fairService.Update(fair);
                return RedirectToAction("Index");
            }
            return View(fair);
        }

        // GET: Administrator/Fairs/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fair fair = fairService.GetById(id);
            if (fair == null)
            {
                return HttpNotFound();
            }
            return View(fair);
        }

        // POST: Administrator/Fairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Fair fair = fairService.GetById(id);
            fairService.RemoveForce(fair);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            
            base.Dispose(disposing);
        }
    }
}

WebUII/Areas/Administrator/Controllers/SalloonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.FW.Context;
using Model.FW.Entity;
using Service.FW.Concrete;

namespace WebUII.Areas.Administrator.Controllers
{
    //[Authorize(Roles = "admin")]
    public class SalloonsController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        SalloonService salloonService = new SalloonService();

        // GET: Administrator/Salloons
        public ActionResult Index()
        {
            return View(salloonService.GetList());
        }

        // GET: Administrator/Salloons/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salloon salloon =salloonService.GetById(id);
            if (salloon == null)
            {
                return HttpNotFound();
            }
            return View(salloon);
        }

        // GET: Administrator/Salloons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Salloons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SalloonName,WhichSector,StandNumber")] Salloon salloon)
        {
            if (ModelState.IsValid)
            {
                salloon.ID = Guid.NewGuid();
                salloonService.Create(salloon);
                
                return RedirectToAction("Index");
            }

            return View(salloon);
        }

        // GET: Administrator/Salloons/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salloon salloon = salloonService.GetById(id);
            if (salloon == null)
            {
                return HttpNotFound();
            }
            return View(salloon);
        }

        // POST: Administrator/Salloons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SalloonName,WhichSector,StandNumber")] Salloon salloon)
        {
            if (ModelState.IsValid)
            {
                salloonService.Update(salloon);
                return RedirectToAction("Index");
            }
            return View(salloon);
        }

        // GET: Administrator/Salloons/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salloon salloon = salloonService.GetById(id);
            if (salloon == null)
            {
                return HttpNotFound();
            }
            return View(salloon);
        }

        // POST: Administrator/Salloons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Salloon salloon = salloonService.GetById(id);
            salloonService.RemoveForce(salloon);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
        
            base.Dispose(disposing);
        }
    }
}

WebUII/Areas/Administrator/Controllers/StandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.FW.Context;
using Model.FW.Entity;
using Service.FW.Concrete;

namespace WebUII.Areas.Administrator.Controllers
{
    //[Authorize(Roles = "admin")]
    public class StandsController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        StandService standService = new StandService();

        // GET: Administrator/Stands
        public ActionResult Index()
        {
            return View(standService.GetList());
        }

        // GET: Administrator/Stands/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stand stand =standService.GetById(id);
            if (stand == null)
            {
                return HttpNotFound();
            }
            return View(stand);
        }

        // GET: Administrator/Stands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Stands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,StandNumber,M2,M2Price")] Stand stand)
        {
            if (ModelState.IsValid)
            {
                stand.ID = Guid.NewGuid();
                standService.Create(stand);
                return RedirectToAction("Index");
            }

            return View(stand);
        }

        // GET: Administrator/Stands/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stand stand =standService.GetById(id);
            if (stand == null)
            {
                return HttpNotFound();
            }
            return View(stand);
        }

        // POST: Administrator/Stands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,StandNumber,M2,M2Price")] Stand stand)
        {
            if (ModelState.IsValid)
            {
                standService.Update(stand);
                return RedirectToAction("Index");
            }
            return View(stand);
        }

        // GET: Administrator/Stands/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stand stand = standService.GetById(id);
            if (stand == null)
            {
                return HttpNotFound();
            }
            return View(stand);
        }

        // POST: Administrator/Stands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Stand stand =standService.GetById(id);
            standService.RemoveForce(stand);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
           
            base.Dispose(disposing);
        }
    }
}

WebUII/Areas/Administrator/Controllers/VisitorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.FW.Context;
using Model.FW.Entity;
using Service.FW.Concrete;

namespace WebUII.Areas.Administrator.Controllers
{
    //[Authorize(Roles = "admin")]
    public class VisitorsController : Controller
    {
        //private AppDbContext db = new AppDbContext();
        VisitorService visitorService = new VisitorService();

        // GET: Administrator/Visitors
        public ActionResult Index()
        {
            return View(visitorService.GetList());
        }

        // GET: Administrator/Visitors/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                Visitor visitor = visitorService.GetById(id);

                if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // GET: Administrator/Visitors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Visitors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,CompanyName,PhoneNumber,MailAdress,Occupation")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                visitor.ID = Guid.NewGuid();
               visitorService.Create(visitor);
               
                return RedirectToAction("Index");
            }

            return View(visitor);
        }

        // GET: Administrator/Visitors/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitor visitor =visitorService.GetById(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // POST: Administrator/Visitors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,CompanyName,PhoneNumber,MailAdress,Occupation")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                visitorService.Update(visitor);
                return RedirectToAction("Index");
            }
            return View(visitor);
        }

        // GET: Administrator/Visitors/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visitor visitor = visitorService.GetById(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // POST: Administrator/Visitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Visitor visitor =visitorService.GetById(id);
            visitorService.RemoveForce(visitor);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
          
            base.Dispose(disposing);
        }
    }
}

WebUII/Areas/Administrator/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="~/Content/img/favicon.png">

    <title>FairWorks Administrator Page</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/style-responsive.css" rel="stylesheet" />



    <link href="~/Content/datatable/css/datatables-bootstrap3.css" rel="stylesheet" /> 
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="~/Content/js/html5shiv.js"></script>
      <script src="~/Content/js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a href="~/Content/index.html" class="logo">FAIRWORKS</a>
            <!--logo end-->
            
            <div class="top-nav ">
                <!--search & user info start-->
                <ul class="nav pull-right top-menu">
                    <li>
                        <input type="text" class="form-control search" placeholder="Search">
                    </li>
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="~/Content/#">
                            <img alt="" src="">
                            <span class="username">@User.Identity.Name</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            
                          
                            <li><a href=""><i class="icon-key"></i> Log Out</a></li>
                            
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!--search & user info end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a href="~/Content/index.html">
                            <i class="icon-dashboard"></i>
                            <span>FairWorks Administrator</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-tags"></i>
                            <span>Şirketler</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Şirket Listesi", "Index", "Companies")
                            </li>
                            <li>
                                @Html.ActionLink("Şirket Ekleme", "Create", "Companies")
                            </li>
                            @*<li>
                                @Html.ActionLink("Şirket Silme", "Delete", "Companies")
                            </li>*@
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-folder-open"></i>
                            <span>Fuar Katılımcıları</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Fuar Katılımcı Listesi", "Index", "FairParticipants")
                            </li>
                            <li>
                                @Html.ActionLink("Katılımcı Ekleme", "Create", "FairParticipants")
                            </li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-user"></i>
                            <span>Fuar İşlemleri</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Fuar Listesi", "Index", "Fairs")
                            </li>
                            <li>
                                @Html.ActionLink("Fuar Ekleme", "Create", "Fairs")
                            </li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-user"></i>
                            <span>Salon İşlemleri</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Salon Listeleme", "Index", "Salloons")
                            </li>
                            <li>
                                @Html.ActionLink("Salon Ekleme", "Create", "Salloons")
                            </li>


                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-user"></i>
                            <span>Stand İşlemleri</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Stand Listesi", "Index", "Stands")
                            </li>
                            <li>
                                @Html.ActionLink("Stand Ekleme", "Create", "Stands")
                            </li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="~/Content/javascript:;">
                            <i class="icon-user"></i>
                            <span>Ziyaretçiler</span>
                        </a>
                        <ul class="sub">
                            <li>
                                @Html.ActionLink("Ziyaretçi Listesi", "Index", "Visitors")
                            </li>
                            <li>
                                @Html.ActionLink("Ziyaretçi Ekle", "Create", "Visitors")
                            </li>
                        </ul>
                    </li>
                    <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                2021 &copy; FairWorks by İBP
                <a href="~/Content/#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/Content/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/Content/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/Content/js/owl.carousel.js"></script>
    <script src="~/Content/js/jquery.customSelect.min.js"></script>
    <script src="~/Content/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="~/Content/js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="~/Content/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="~/Content/js/sparkline-chart.js"></script>
    <script src="~/Content/js/easy-pie-chart.js"></script>
    <script src="~/Content/js/count.js"></script>

    <script>

        //owl carousel

        $(document).ready(function () {
            $("#owl-demo").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true,
                autoPlay: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

    </script>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/datatable/js/datatables-bootstrap3.js"></script>
    <script>
        $(document).ready(function () {
            $('#example-table').dataTable();
        });
    </script>


</body>
</html>